// <auto-generated />
namespace PD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddStartDateEndDateToSession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStartDateEndDateToSession));
        
        string IMigrationMetadata.Id
        {
            get { return "201410141039396_AddStartDate&EndDateToSession"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
