// <auto-generated />
namespace PD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UpdateCourseTable_AddColumns_Location_SessionsOccur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateCourseTable_AddColumns_Location_SessionsOccur));
        
        string IMigrationMetadata.Id
        {
            get { return "201410141024043_UpdateCourseTable_AddColumns_Location_SessionsOccur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
