// <auto-generated />
namespace PD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CreateCountryTable_RegionTable_AddColumnRegionAndCountryInUserProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateCountryTable_RegionTable_AddColumnRegionAndCountryInUserProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201409240859200_CreateCountryTable_RegionTable_AddColumnRegionAndCountryInUserProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
