app.config(function ($translateProvider) {
    $translateProvider.translations('ar-sa', {
        TITLE: 'بالعربى',
        Foo: 'ده',

        //menus
        Dashboard: 'لوحة اعدادتى',
        Catalog: 'دليل الدورات التدريبية',
        Create_Course: 'دورة تدريبية جديدة',
        Welcome:'مرحبا',
        Search: 'ابحث',
        Administration: 'ادارة الدورات التدريبية',

        'Create Course': 'دورة تدريبية جديدة',
        'Enroll':'تسجيل',
        'Un-Enroll': 'إلغاء التسجيل',
        'Add':'اضافة',
        'Save': 'حفظ',
        'Cancel': 'إلغاء',
        
        //Create Course
        'Select Section': 'اختر قسم',
        'Select Category': 'اختر فئة',
        'Online Course': 'عبر الانترنت',
        'Face to face Course': 'حضورى',
        'Number of seats': 'عدد المقاعد',
        'Basic Info': 'البيانات الأساسية',
        'Course Name is required': 'من فضلك أدخل اسم الدورة التدريبية',
        'Course Section is required': 'من فضلك اختر القسم',
        'Course Cetegory is required.': 'من فضلك اختر الفئة',
        'Course name should be unique under the same category': 'اسم الدورة التدريبية يجب أن يكون غير مكرر تحت نفس الفئة',
        'Course Brief is required.': 'من فضلك أدخل نبذة عن الدورة التدريبية',
        'Please write a short description about the course.': 'من فضلك أدخل نبذة عن الدورة التدريبية',
        'Tip: Upload a clean, non-pixelated image that is minimum 725X330.': '725X330 من فضلك أدخل صورة غير منقطة على الأقل',
        'About the Course is required.': 'من فضلك أدخل وصف عن الدورة التدريبية',
        'Course Basic Info': 'البيانات الأساسية',
        'Course Details': 'تفاصيل الدورة التدريبية',
        'Participants Will': 'سيتمكن المشاركون من',
        'Course Schedule': 'خطة التدريب',
        'Start Date': 'تاريخ البدء',
        'End Date': 'تاريخ الانتهاء',
        'Start Date is required.': 'من فضلك أدخل تاريخ البدء',
        'End Date is required.':'من فضلك أدخل تاريخ الانتهاء',
        'Instructors': 'المدربين',
        'Course Outlines': 'المحتويات',
        'Add Content': 'إضافة محتوى',
        'Course Competencies': 'المهارات المكتسبة',
        'Course FAQs': 'الأسئلة المتداولة',
        'Course Name': 'اسم الدورة التدريبية',
        'Short Name': 'الاسم القصير',
        'Course Section': 'قسم الدورة التدريبية',
        'Course Category': 'فئة الدورة التدريبية',
        'Course Image': 'صورة',
        'Course Brief': 'نبذة',
        'About The Course': 'عن الدورة التدريبية',
        'Target Audience': 'الفئة المستهدفة',
        'Required Background': 'الخبرات المطلوبة',
        'Instructor Name': 'اسم المدرب',
        'Multiple instructor names should be comma separated."ex. John Doe,Pam Taylor"':'لكتابة عدة مدربين يرجى الفصل بين الأسامي بالفاصلة "مثال:أحمد محمد,أسماء محمود"',
        'Outline & Content': 'المحتوى',
        'Add New Session': 'اضافه محاضرة',
        'Session Name': 'اسم المحاضرة',
        'Publishing Date': 'تاريخ النشر',
        'Publishing Date is required': 'يرجى ادخال تاريخ النشر',
        'Objectives': 'الأهداف',
        'Material Title': 'المحتوى',
        'Material URL': 'عنوان المحتوي',
        'Material URL is required.': 'من فضلك أدخل عنوان المحتوى',
        'Published': 'تاريخ النشر',
        'Session Content': 'محتوى المحاضرة',
        'You should add at least one session': 'يجب اضافة و حفظ محاضرة واحدة على الأقل',
        'Question': 'السؤال ',
        'Answer': 'الإجابة',
        'Save FAQ': 'حفظ السؤال',
        'Publish': 'انشر الدورة التدريبية',
        'Update': 'تحديث',
        'Your course is saved successfully': 'تم حفظ الدورة بنجاح',
        'Your course is updated successfully': 'تم تحديث الدورة بنجاح',
        'Next': 'التالى ',
        'Back': 'السابق',
        'Please fill all missing mandatory fields before publishing your course': 'من فضلك املأ جميع البيانات المطلوبة قبل نشر الدورة التدريبية',
        'Invalid file, please upload an image': 'من فضلك ارفع صورة',
        'Sessions Occur': 'المحاضرات تتكرر',
        'Location': 'مكان الدورة التدريبية',
        'Select Sessions Occur':'اختر تكرار المحاضرات',

        //Course Catalouge
        'There are no courses in this category': 'لا يوجد دورات تدريبية في هذا القسم',
        'Please select another category or use Search option': 'من فضلك اختر قسم آخر أو استخدم البحث',
        'All': 'الكل',
        'Filter By Competencies': 'البحث بالمهارات المكتسبة',
        'By': 'يقدمه',
        'Competencies': 'المهارات المكتسبة',
        'Filter': 'ابحث',
        'Register': 'تسجيل',
        'Pending Approval': 'انتظار للموافقة',
        //Course Details:
        'Section': 'القسم',
        'Number Of Seats': 'عدد المقاعد',
        'Category': 'الفئة',
        'Online Course': 'دورة تدريبية عبر الإنترنت',
        'Overview': 'نظرة عامة',
        'FAQ': 'الأسئلة المتداولة',
        'Content': 'المحتوى',
        'Mark as Complete': 'إتمام',
        'Start': 'بدء',
        'Completed': 'تم الإنتهاء من المحاضرة',
        'Expand, Collapse the answer': 'توسيع، طي الإجابة',
        //لا توجد أسئلة متداولة لعرضها
        //لا توجد مهارات مكتسبة لهذه الدورة التدريبية
        //يرجى إلغاء بعض المكتسبات المهنية
        //مكتسبات مهنية مختارة

        //Dashboard:
        'My Training Plan': "خطة التدريب الخاص بي",
        'No_Courses_TrainingPlan': "ليس لديك دورات تدريبية في خطة التدريب",
        'View_Courses': 'أظهر الدورات التدريبية',
        'Active': 'النشطة',
        'UpComing': 'القادمة',
        'completed_courses': 'المنتهية',
        'Remaining Sessions': 'الدورات المتبقية',
        'of': 'من',

        //Profile:
        'About': 'عني',
        'Years': 'سنوات',
        'Year': 'سنة',
        'My Profile': 'صفحتي الشخصية',
        'Edit Profile': 'تعديل الصفحة الشخصية',
        'Profile Image': 'الصورة الشخصية',
        'Edit': 'تعديل',
        'Firm name': 'اسم الشركة',
        'Firm Name is Required': 'من فضلك أدخل اسم الشركة',
        'Please enter Firm name less than 255 characters': 'من فضلك أدخل اسم الشركة أقل من 255 حرف',
        'Name': 'الاسم',
        'Title': 'المسمى الوظيفي',
        'Title is Required':'من فضلك أدخل المسمى الوظيفي',
        'Please enter Title less than 255 characters': 'من فضلك أدخل المسمى الوظيفي أقل من 255 حرف',
        'Location': 'موقع العمل',
        'Please enter Location less than 255 characters': 'من فضلك أدخل موقع العمل أقل من 255 حرف',
        'Start Date is required': 'من فضلك أدخل تاريخ البدء',
        'End Date is required': 'من فضلك أدخل تاريخ الانتهاء',
        'About Me': 'معلومات عني',
        'Place of work': 'مكان العمل',
        'Country': 'المدينة',
        'Region': 'المنطقة',
        'Organisation name': 'اسم المنظمة',
        'Time Period': 'الفترة',
        'I currently work there': 'أنا حاليا اعمل هناك',
        'Job Description': 'طبيعة العمل',
        'Please enter Job Description less than 1000 characters' : 'من فضلك أدخل طبيعة العمل أقل من 1000 حرف',
        'Remove this entry': 'إزالة هذا السجل',
        'Experience': 'الخبرة',
        'Interests': 'الاهتمامات',
        'What are your areas of interest?': 'ما هي اهتماماتك؟',
        'Find Me here': 'اعثر عليّ هنا',
        'Personal Details': 'معلومات شخصية',
        'Birthday': 'تاريخ الميلاد',
        'Select Day': 'اختر يوم',
        'Select Month': 'اختر شهر',
        'Gender': 'النوع',
        'Male': 'ذكر',
        'Female': 'أنثى',
        'Select Country': 'اختر البلد',
        'Select Region': ' اختر المدينة',
        'School': 'المدرسة',
        'Joined In': 'تاريخ الالتحاق',
        'Type in a search term': 'اكتب مصطلح البحث',
        'No results': 'لا توجد نتائج',
        'Searching': 'جاري البحث',
        'Gender is required': 'من فضلك اختر بين الجنسين',
        'please enter text less than 100 character':'من فضلك أدخل نص أقل من 100 حرف',
        'No Data Inserted': 'لا يوجد بيانات',
        'Add Your Interests': 'أضف اهتماماتك',
        'Add Your Social Media Links': 'أضف روابط وسائل التواصل الاجتماعي',
        'Add Experience': 'أضف خبرة',
        'Add Your Biography': 'أضف سيرتك',
        'Birthdate': 'تاريخ الميلاد',
        'Add Your Personal Details': 'أدخل معلوماتك الشخصية',
        'Marital Status': 'الحالة الزوجية',
        'Course Type': 'النوع',
        'Change Image' : 'تغير الصورة',
        'Select your Birthday' : 'اختر تاريخ ميلادك',
        
        //Push Courses:
        'Push Courses': 'انشر الدورات التدريبية',
        'Select the courses that you want to push to the trainees':'اختر الدورات التدريبية التي تريد نشرها للمتدربين',
        'Courses selected': 'دورة تدريبية مُختارة',
        'Unselect all': 'إلغاء اختيار كل الدورات',
        'Assign To': 'تعيين ل',
        'Assign': 'تعيين',
        'Cancel Pushing':'إلغاء النشر',
        'Assign Courses': 'نشر الدورات التدريبية',
        'Push these courses': 'نشر هذه الدورات التدريبية',
        'One course at least should be available to be pushed.': 'دورة تدريبية واحدة على الأقل ينبغي أن تكون متوفرة للنشر'
	});
});
