// <auto-generated />
namespace PD.DataLayer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddMaritalStatusTableAndForeginKeyInUserProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMaritalStatusTableAndForeginKeyInUserProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201410011347065_AddMaritalStatusTableAndForeginKeyInUserProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
