// <auto-generated />
namespace PD.DataLayer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ComptencyTitle_MaxLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComptencyTitle_MaxLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201409171407375_ComptencyTitle_MaxLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
